#!/bin/bash

#####################################
# DigiScrap Nautilus Script
# Batch converts images to JPG
#
# More info at...
# mandytonks.net/digiartgallery/
#
# Absolutely no guarantees, warranties
# or any other sort of -ies provided
# Use at your own risk.
#
# Uses imagemagick.
#####################################

while [ $# -gt 0 ]; do
	file=$1
	newfile=`echo "$file" | sed 's/\.\w*$/_sm.jpg/'`
	/usr/bin/convert -quality 70 -resize 2000 "$file" jpeg:"$newfile"
	shift
done
