#!/bin/bash

while [ $# -gt 0 ]; do
	file=$1
	newfile=`echo "$file" | sed 's/\.pdf$/-cmyk.pdf/'`
	gs -o "$newfile" -sDEVICE=pdfwrite -dUseCIEColor -sProcessClolorModel=DeviceCMYK -sColorConversionStrategy=CMYK -sColorConversionStrategyForImages=CMYK "$file"
	shift
done
