#!/bin/bash

while [ $# -gt 0 ]; do
	file=$1
	newfile=`echo "$file" | sed 's/\.pdf$/-sm.pdf/'`
	gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.5 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile="$newfile" "$file"
	shift
done
