#!/bin/bash

# Script that reads the date the last selected photo was taken,
# asks the user for a folder name and creates a folder named 

#     YYYY-MM-DD folder name

# and moves all the photos there

ROOTDIR=/mnt/e4ab62c5-8706-467f-a8cc-85f0e590fcb0/photos/

DATE=`exiftool ${@: -1} | grep -m 1 Create\ Date | sed 's/Create Date[ ]\+: [0-9]\{4\}:\(.*\) .*/\1/g' | sed s/:/-/g | tr -d '\n'`
YEAR=`exiftool ${@: -1} | grep -m 1 Create\ Date | sed 's/Create Date[ ]\+: \([0-9]\{4\}\):.* .*/\1/g' | sed s/:/-/g | tr -d '\n'`
DIRNAME=`zenity --entry --text="Folder name" #--entry-text="$DATE "`
DIRNAMEFULL="$YEAR/$DATE $DIRNAME"
mkdir "$ROOTDIR/$DIRNAMEFULL"
mv $@ "$ROOTDIR/$DIRNAMEFULL"
nautilus "$ROOTDIR/$DIRNAMEFULL"
