#!/bin/bash

while [ $# -gt 0 ]; do
	file=$(basename "$1")
	scp "$1" qwazix@c.d-e.gr:/var/www/qwazix.com/public_html/shared/
	url="http://qwazix.com/shared/$file"
	echo "$url" | xclip -selection clipboard
	shift
done
